FROM ubuntu:latest

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y --no-install-recommends \
                bison \
                curl  \
                flex \
                ca-certificates \
                build-essential \
                python3-pip \
        && rm -rf /var/lib/apt/lists/*

# Get Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# copy the project code
COPY cpsnark-sm /app/cpsnark-sm

# set work directory
WORKDIR /app/cpsnark-sm

RUN cargo build
RUN cargo bench --bench membership_hash
